# Generated by Django 4.2.13 on 2024-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='dst_port',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
