# Generated by Django 4.2.13 on 2024-06-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_app', '0002_packet_dst_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=100)),
                ('src_ip', models.CharField(max_length=100)),
                ('dst_ip', models.CharField(max_length=100)),
                ('dst_port', models.IntegerField()),
                ('report', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='packet',
            name='attack_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='is_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='packet',
            name='dst_ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packet',
            name='dst_port',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packet',
            name='protocol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='packet',
            name='src_ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
    ]
